--
-- PostgreSQL database dump
--

\restrict rpoXT8tcrIPlhXhUtabiConvb5nRpZkMT9KdzrfegP4PWl0yYrRWyNGyedYVqlz

-- Dumped from database version 17.11 (Homebrew)
-- Dumped by pg_dump version 17.11 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: frontend_member; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.frontend_member (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    nickname character varying(20) NOT NULL,
    password_hash character varying(128) NOT NULL,
    address character varying(200) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: frontend_member_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.frontend_member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.frontend_member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: frontend_member; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.frontend_member (id, name, nickname, password_hash, address, created_at, updated_at) FROM stdin;
1	김형준	나비	pbkdf2_sha256$1500000$7T3JYpSD8Nw4CcMRGD8i0t$veK63EROtKHKuFYFfNWUYaor2MjIr5kU1HLxbmzRVls=	경기도 수원시	2026-09-18 10:12:09.652473+09	2026-09-18 10:12:09.652483+09
\.


--
-- Name: frontend_member_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.frontend_member_id_seq', 1, true);


--
-- Name: frontend_member frontend_member_nickname_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.frontend_member
    ADD CONSTRAINT frontend_member_nickname_key UNIQUE (nickname);


--
-- Name: frontend_member frontend_member_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.frontend_member
    ADD CONSTRAINT frontend_member_pkey PRIMARY KEY (id);


--
-- Name: frontend_member_nickname_0b51719e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX frontend_member_nickname_0b51719e_like ON public.frontend_member USING btree (nickname varchar_pattern_ops);


--
-- PostgreSQL database dump complete
--

\unrestrict rpoXT8tcrIPlhXhUtabiConvb5nRpZkMT9KdzrfegP4PWl0yYrRWyNGyedYVqlz

